# fly.toml app configuration file generated for plantswap on 2025-01-14T22:27:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plantswap'
primary_region = 'fra'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
