name: Build and Test with Docker Compose

on: push

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Poethepoet
        run: pipx install poethepoet

      - name: Start compose with Poethepoet
        run: poe compose-test

      - name: Shut down services
        run: poe compose-down
